**Dataset Description**

## The dataset contains information about road traffic accidents with the following columns:

`Time`: Time of the accident

`Day_of_week`: Day of the week when the accident occurred

`Age_band_of_driver`: Age group of the driver

`Sex_of_driver`: Gender of the driver

`Educational_level`: Educational level of the driver

`Vehicle_driver_relation`: Relationship of the driver to the vehicle

`Driving_experience`: Driving experience of the driver

`Type_of_vehicle`: Type of vehicle involved in the accident

`Owner_of_vehicle`: Owner of the vehicle

`Service_year_of_vehicle`: Service years of the vehicle

`Area_accident_occured`: Area where the accident occurred

`Lanes_or_Medians`: Lanes or medians at the accident site

`Road_allignment`: Road alignment at the accident site

`Types_of_Junction`: Type of junction at the accident site

`Road_surface_type`: Type of road surface at the accident site

`Road_surface_conditions`: Road surface conditions at the accident site

`Light_conditions`: Light conditions at the time of the accident

`Weather_conditions`: Weather conditions at the time of the accident

`Type_of_collision`: Type of collision

`Number_of_vehicles_involved`: Number of vehicles involved in the accident

`Number_of_casualties`: Number of casualties in the accident

`Vehicle_movement`: Movement of the vehicle during the accident

`Casualty_class`: Class of casualty (driver, passenger, pedestrian)

`Sex_of_casualty`: Gender of the casualty

`Age_band_of_casualty`: Age group of the casualty

`Casualty_severity`: Severity of the casualty

`Work_of_casuality`: Occupation of the casualty

`Fitness_of_casuality`: Fitness of the casualty

`Pedestrian_movement`: Movement of the pedestrian

`Cause_of_accident`: Cause of the accident

`Accident_severity`: Severity of the accident

# Tasks

##1. Data Cleaning

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from plotly import graph_objects as go
import plotly.express as px

import datetime as dt

In [5]:
df = pd.read_csv('/content/Task (1) Dataset.csv')

In [6]:
df.head()

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
0,17:02:00,Monday,18-30,Male,Above high school,Employee,1-2yr,Automobile,Owner,Above 10yr,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Moving Backward,Slight Injury
1,17:02:00,Monday,31-50,Male,Junior high school,Employee,Above 10yr,Public (> 45 seats),Owner,5-10yrs,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury
2,17:02:00,Monday,18-30,Male,Junior high school,Employee,1-2yr,Lorry (41?100Q),Owner,NaN,...,Going straight,Driver or rider,Male,31-50,3,Driver,NaN,Not a Pedestrian,Changing lane to the left,Serious Injury
3,1:06:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Public (> 45 seats),Governmental,NaN,...,Going straight,Pedestrian,Female,18-30,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
4,1:06:00,Sunday,18-30,Male,Junior high school,Employee,2-5yr,NaN,Owner,5-10yrs,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12316 entries, 0 to 12315
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Time                         12316 non-null  object
 1   Day_of_week                  12316 non-null  object
 2   Age_band_of_driver           12316 non-null  object
 3   Sex_of_driver                12316 non-null  object
 4   Educational_level            11575 non-null  object
 5   Vehicle_driver_relation      11737 non-null  object
 6   Driving_experience           11487 non-null  object
 7   Type_of_vehicle              11366 non-null  object
 8   Owner_of_vehicle             11834 non-null  object
 9   Service_year_of_vehicle      8388 non-null   object
 10  Defect_of_vehicle            7889 non-null   object
 11  Area_accident_occured        12077 non-null  object
 12  Lanes_or_Medians             11931 non-null  object
 13  Road_allignment              12174 non-null  object
 14  Types_of_Junction            11429 non-null  object
 15  Road_surface_type            12144 non-null  object
 16  Road_surface_conditions      12316 non-null  object
 17  Light_conditions             12316 non-null  object
 18  Weather_conditions           12316 non-null  object
 19  Type_of_collision            12161 non-null  object
 20  Number_of_vehicles_involved  12316 non-null  int64
 21  Number_of_casualties         12316 non-null  int64
 22  Vehicle_movement             12008 non-null  object
 23  Casualty_class               12316 non-null  object
 24  Sex_of_casualty              12316 non-null  object
 25  Age_band_of_casualty         12316 non-null  object
 26  Casualty_severity            12316 non-null  object
 27  Work_of_casuality            9118 non-null   object
 28  Fitness_of_casuality         9681 non-null   object
 29  Pedestrian_movement          12316 non-null  object
 30  Cause_of_accident            12316 non-null  object
 31  Accident_severity            12316 non-null  object
dtypes: int64(2), object(30)
memory usage: 3.0+ MB

In [8]:
df.sample(10)

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
5097,7:55:00,Wednesday,Unknown,Female,Junior high school,Employee,1-2yr,Lorry (41?100Q),Owner,Unknown,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,Changing lane to the left,Slight Injury
6704,20:30:00,Saturday,Unknown,Male,High school,Employee,Above 10yr,Public (13?45 seats),Owner,Unknown,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,Moving Backward,Serious Injury
6828,16:12:00,Saturday,18-30,Male,Junior high school,Employee,5-10yr,Public (> 45 seats),Owner,Unknown,...,Going straight,Driver or rider,Male,18-30,3,Driver,Normal,Not a Pedestrian,Changing lane to the left,Slight Injury
1761,13:15:00,Thursday,18-30,Male,Junior high school,Employee,1-2yr,Automobile,Owner,NaN,...,Going straight,Pedestrian,Male,18-30,3,Self-employed,Normal,Unknown or other,Changing lane to the left,Slight Injury
4793,19:28:00,Wednesday,18-30,Male,NaN,NaN,NaN,Other,Owner,Above 10yr,...,Stopping,Driver or rider,Male,18-30,3,NaN,NaN,Not a Pedestrian,Changing lane to the left,Slight Injury
10063,8:28:00,Monday,18-30,Male,Junior high school,Employee,5-10yr,Lorry (41?100Q),Owner,Unknown,...,Going straight,Driver or rider,Male,18-30,2,NaN,NaN,Not a Pedestrian,Driving under the influence of drugs,Slight Injury
5757,11:30:00,Wednesday,Unknown,Male,Junior high school,Employee,Above 10yr,Lorry (41?100Q),Owner,Unknown,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
8285,16:05:00,Wednesday,31-50,Female,Junior high school,Employee,5-10yr,Automobile,Owner,NaN,...,Going straight,Driver or rider,Male,31-50,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Serious Injury
3399,22:30:00,Thursday,18-30,Male,Junior high school,Employee,Above 10yr,Motorcycle,Owner,Unknown,...,Going straight,Pedestrian,Female,31-50,3,Self-employed,Normal,Not a Pedestrian,Getting off the vehicle improperly,Slight Injury
6158,17:30:00,Wednesday,Under 18,Male,Elementary school,Employee,5-10yr,Lorry (11?40Q),Owner,Unknown,...,Going straight,na,na,na,na,Other,Normal,Not a Pedestrian,No priority to vehicle,Serious Injury

In [9]:

column_to_drop = [
                  'Educational_level',
                 'Vehicle_driver_relation',
                 'Owner_of_vehicle',
                  'Casualty_class',
                  'Sex_of_casualty',
                  'Age_band_of_casualty',
                  'Casualty_severity',
                  'Fitness_of_casuality',
                  'Pedestrian_movement',
                  'Work_of_casuality'
                  ]

df = df.drop(column_to_drop, axis=1)

In [10]:
df['Driving_experience'].isnull().sum()

np.int64(829)

In [11]:
df['Driving_experience'].fillna('Unknown' , inplace=True)

/tmp/ipykernel_3901/3994973854.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Driving_experience'].fillna('Unknown' , inplace=True)

In [12]:
df['Type_of_vehicle'].isnull().sum()

np.int64(950)

In [13]:
df['Type_of_vehicle'].fillna(df['Type_of_vehicle'].mode()[0] , inplace=True)

/tmp/ipykernel_3901/1851984226.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Type_of_vehicle'].fillna(df['Type_of_vehicle'].mode()[0] , inplace=True)

In [14]:
df['Service_year_of_vehicle'].value_counts()

Service_year_of_vehicle
Unknown       2883
2-5yrs        1792
Above 10yr    1324
5-10yrs       1280
1-2yr          827
Below 1yr      282
Name: count, dtype: int64

In [15]:
df['Service_year_of_vehicle'].isnull().sum() # a lot of 'unknown' and missing values , so i will drop the column

np.int64(3928)

In [16]:
df.drop('Service_year_of_vehicle' , axis=1 , inplace=True)

In [17]:
df['Defect_of_vehicle'].value_counts()

Defect_of_vehicle
No defect    7777
7              76
5              36
Name: count, dtype: int64

In [18]:
df['Defect_of_vehicle'].isnull().sum() # a lot of null values , most of it (no defect) , drop the column

np.int64(4427)

In [19]:
df.drop('Defect_of_vehicle' , axis=1 , inplace=True)

In [20]:
df['Area_accident_occured'].isnull().sum()

np.int64(239)

In [21]:
df = df.dropna(subset=['Area_accident_occured'])

In [22]:
df['Lanes_or_Medians'].isnull().sum()

np.int64(331)

In [24]:
df['Lanes_or_Medians'].fillna('Unknown' , inplace=True)

In [25]:
df['Road_allignment'].isnull().sum()

np.int64(120)

In [26]:
df = df.dropna(subset=['Road_allignment'])

In [27]:
df['Types_of_Junction'].isnull().sum()

np.int64(866)

In [29]:
df['Types_of_Junction'].fillna('Unknown' , inplace=True)

In [30]:
df['Road_surface_type'].isna().sum()

np.int64(169)

In [31]:
df = df.dropna(subset=['Road_surface_type'])

In [32]:
df['Type_of_collision'].isnull().sum()

np.int64(151)

In [33]:
df = df.dropna(subset=['Type_of_collision'])

In [34]:
df['Vehicle_movement'].isnull().sum()

np.int64(293)

In [36]:
df['Vehicle_movement'].fillna('Unknown' , inplace=True)

In [49]:
for col in df.columns:
    print(f"'{col}'")

'Time'
'Day_of_week'
'Age_band_of_driver'
'Sex_of_driver'
'Driving_experience'
'Type_of_vehicle'
'Area_accident_occured'
'Lanes_or_Medians'
'Road_allignment'
'Types_of_Junction'
'Road_surface_type'
'Road_surface_conditions'
'Light_conditions'
'Weather_conditions'
'Type_of_collision'
'Number_of_vehicles_involved'
'Number_of_casualties'
'Vehicle_movement'
'Cause_of_accident'
'Accident_severity'

In [53]:
df['Time'] = pd.to_datetime(df['Time'])

In [54]:
df['Date'] = df['Time'].dt.date

In [55]:
df['hour'] = df['Time'].dt.hour

In [56]:
df['Type_of_vehicle'] = df['Type_of_vehicle'].str.replace(r'Lorry.*', 'Lorry', regex=True)
df['Type_of_vehicle'] = df['Type_of_vehicle'].str.replace(r'lorry.*', 'Lorry', regex=True)
df['Type_of_vehicle'] = df['Type_of_vehicle'].str.replace(r'Public.*', 'Public', regex=True)

In [57]:
fig = go.Figure(data=[go.Histogram(x=df.Number_of_casualties)])

fig.update_layout(title=dict(text="Distribution of Number of casualties"))
fig.show()

In [58]:
counts_accident = df['Cause_of_accident'].value_counts()
counts_accident = pd.DataFrame(counts_accident)

fig = px.bar(counts_accident, x=counts_accident.index, y='count', title = 'Distribution of Accidents by Cause' )
fig.update_layout(xaxis_title='Couse of Accident', yaxis_title='Count')
fig.show()

In [59]:
counts_area = df['Area_accident_occured'].value_counts()
counts_area = pd.DataFrame(counts_area)

fig = px.bar(counts_area, x=counts_area.index, y='count', title = 'Accident Count by Area' )
fig.update_layout(xaxis_title='Area', yaxis_title='Count')
fig.show()

In [60]:
filtered_df = df[df['Area_accident_occured'] == 'Office areas']

length = len(filtered_df)
print(length)

grouped_df = filtered_df.groupby('Cause_of_accident').size().reset_index(name='count')
grouped_df = grouped_df.sort_values(by='count', ascending=False)

percentage_couse = (grouped_df['count'] / length) * 100
grouped_df['percentage'] = percentage_couse


fig = px.pie(grouped_df, values='percentage', names='Cause_of_accident', title='Causes of accidents in the office area')
fig.show()

3347

In [61]:
filtered_df = df[df['Area_accident_occured'] == 'Office areas']

office_accidents_by_hour = filtered_df.groupby('hour')['Area_accident_occured'].count()

office_accidents_by_hour = pd.DataFrame(office_accidents_by_hour)
office_accidents_by_hour

fig = px.line(office_accidents_by_hour, x=office_accidents_by_hour.index, y="Area_accident_occured", title='Count of office accidents by hour')
fig.update_layout(xaxis_title='Hour', yaxis_title='Count')
fig.show()

In [62]:

filtered_df = df[df['Accident_severity'] == 'Serious Injury']

num_accident = df.groupby('Type_of_vehicle').size().reset_index(name='count')

num_serious_accident = filtered_df.groupby('Type_of_vehicle').size().reset_index(name='count')

num_serious_accident['percentage'] = (num_serious_accident['count'] / num_accident['count']) * 100

num_serious_accident = num_serious_accident.sort_values(by='percentage', ascending=False)

fig = px.bar(num_serious_accident, x='Type_of_vehicle', y='percentage', title='Percentage of Serious Injuries by Vehicle Type')
fig.update_layout(xaxis_title='Type of Vehicle', yaxis_title='Percentage', yaxis_range=[0, 50])
fig.show()

In [63]:
ages= df['Age_band_of_driver'].value_counts()
ages = pd.DataFrame(ages)
ages.rename(columns={'Age_band_of_driver':'count'},inplace=True)


total = len(df)
ages['percentage'] = (ages['count']/total)*100

fig = px.pie(ages, values='percentage', names=ages.index, title='Percentage of age groups in committing accidents')
fig.show()

In [64]:
collision_severity = df.groupby(['Type_of_collision', 'Accident_severity']).size().reset_index(name='Count')

fig = px.bar(collision_severity, x='Type_of_collision', y='Count', color='Accident_severity', barmode='group', title='Accident Severity by Collision Type')

fig.update_layout(
    xaxis_title='Collision Type',
    yaxis_title='Accident Count'
)

fig.show()

In [65]:

counts_accident_by_collision = df.groupby('Type_of_collision').size()

count_of_severty = df.groupby(['Type_of_collision','Accident_severity']).size()

avg_severity_by_collision = (count_of_severty / counts_accident_by_collision) * 100
avg_severity_by_collision

Type_of_collision                        Accident_severity
Collision with animals                   Fatal injury          1.212121
                                         Serious Injury       15.757576
                                         Slight Injury        83.030303
Collision with pedestrians               Fatal injury          2.444703
                                         Serious Injury       15.948778
                                         Slight Injury        81.606519
Collision with roadside objects          Fatal injury          1.403509
                                         Serious Injury       15.321637
                                         Slight Injury        83.274854
Collision with roadside-parked vehicles  Serious Injury        9.433962
                                         Slight Injury        90.566038
Fall from vehicles                       Serious Injury       12.903226
                                         Slight Injury        87.096774
Other                                    Serious Injury       12.000000
                                         Slight Injury        88.000000
Rollover                                 Fatal injury          1.052632
                                         Serious Injury       12.894737
                                         Slight Injury        86.052632
Unknown                                  Serious Injury        7.692308
                                         Slight Injury        92.307692
Vehicle with vehicle collision           Fatal injury          1.179695
                                         Serious Injury       13.715443
                                         Slight Injury        85.104862
With Train                               Serious Injury       22.222222
                                         Slight Injury        77.777778
dtype: float64